language: java
sudo: false # faster builds

script: "mvn clean package"

after_success:

deploy:
  provider: releases
  file:
    - /target/ParsiAnalyzer-1.0-SNAPSHOT.jar
    - /target/releases/ParsiAnalyzer-1.0-SNAPSHOT.zip
  skip_cleanup: true
  on:
    tags: true


